org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Can be music, tracker or lyrics
extType=music
extId=tidal_ext
extClass=TidalExtension

extIconUrl=https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://tidal.com&size=128
extName=Tidal Extension
extDescription=Tidal, yay!

extAuthor=Echo
extAuthorUrl=https://github.com/brahmkshatriya/echo

extRepoUrl=
extUpdateUrl=